version: '3.1'
services:
  docker-mysql:
    restart: always
    container_name: fixture_db
    image: mysql
    environment:
      MYSQL_DATABASE: fixture_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 1
  eolt:
    restart: on-failure
    build: ./
    expose:
      - "8090"
    ports:
      - "8090:8080"
    environment:
      WAIT_HOST: mysql:3306
    depends_on:
      - docker-mysql