global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.


scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'holistech'
    metrics_path: /actuator/prometheus

    static_configs:
      - targets:
          # IP in MacOS : ifconfig | grep "inet" | grep -v 127.0.0.1
        - '192.168.1.248:8080'